エミュレータ
-
浮動小数点演算



In [1]:
import os
import torch
import json
import numpy as np

OUTPUT_DIR = "output_train_3"
os.makedirs(OUTPUT_DIR, exist_ok=True)

保存
-
Generatorの保存済みパラメータをint8で保存

In [2]:
import os
import json
import torch

# def export_generator(netG_class,pth_path, OUTPUT_DIR,folder_name="G_q17_list",nz=100, ngf=128, device="cpu"):
#     save_dir = os.path.join(OUTPUT_DIR, folder_name)
#     os.makedirs(save_dir, exist_ok=True)

#     netG = netG_class(nz=nz, ngf=ngf).to(device)
#     state_dict = torch.load(pth_path, map_location=device)
#     netG.load_state_dict(state_dict)
#     netG.eval()

#     meta = {}

#     conv_idx = 0
#     for layer in netG.net:
#         if isinstance(layer, torch.nn.ConvTranspose2d):
#             name = f"net{conv_idx}"
#             conv_idx += 1

#             w = layer.weight.detach()
#             w_list = float_to_int8_list(w)

#             # JSON保存
#             json_path = os.path.join(save_dir, f"{name}_weight_q17_list.json")
#             with open(json_path, "w", encoding="utf-8") as f:
#                 json.dump(w_list, f)

#             # TXT保存
#             txt_path = os.path.join(save_dir, f"{name}_weight_q17_list.txt")
#             with open(txt_path, "w", encoding="utf-8") as f:
#                 f.write(f"{name} weight (Q1.7 int8)\n")
#                 f.write(f"shape = [out_ch][in_ch][4][4]\n")
#                 f.write("value = int8 (real=value/128)\n\n")

#                 # w_list [out_ch][in_ch][kH][kW]
#                 for out_ch_id, oc_block in enumerate(w_list):
#                     f.write(f"=== out_ch {out_ch_id} ===\n")
#                     for in_ch_id, kernel in enumerate(oc_block):
#                         f.write(f" -- in_ch {in_ch_id} --\n")
#                         for row in kernel:
#                             f.write("".join(f"{v:4d}" for v in row) + "\n")
#                         f.write("\n")

#             meta[name] = {"shape":[len(w_list),len(w_list[0]),4,4],"json":os.path.basename(json_path),"txt":os.path.basename(txt_path)}
#     # メタ情報
#     meta_path = os.path.join(save_dir, "meta.json")
#     with open(meta_path, "w", encoding="utf-8") as f:
#         json.dump(meta, f, indent=2)
    
    # return save_dir

            

In [3]:
# import torch
# from torch import nn, optim
# class Generator(nn.Module):
#     def __init__(self, nz=100, ngf=128):
#         super().__init__()
#         self.nz = nz

#         self.net = nn.Sequential(
#             # [B,nz,1,1] → [B,ngf*4,4,4]
#             nn.ConvTranspose2d(nz, ngf*4, 4, 1, 0, bias=False),
#             nn.ReLU(True),

#             # [B,ngf*4,4,4] → [B,ngf*2,8,8]
#             nn.ConvTranspose2d(ngf*4, ngf*2, 4, 2, 1, bias=False),
#             nn.ReLU(True),

#             # [B,ngf*2,8,8] → [B,ngf,16,16]
#             nn.ConvTranspose2d(ngf*2, ngf, 4, 2, 1, bias=False),
#             nn.ReLU(True),

#             # [B,ngf,16,16] -> [B,1,32,32]
#             nn.ConvTranspose2d(ngf, 1, 4, 2, 1, bias=False),
#             nn.Tanh()  # [-1,1]
#         )

   
#     def forward(self,z):
#          # [B,100] →　[B,100,1,1]
#         if z.dim() == 2:
#             z = z.view(z.size(0),z.size(1),1,1)
#         return self.net(z)

In [4]:
# pth_path = os.path.join(OUTPUT_DIR, "netG_float32.pth")

# save_dir = export_generator(
#     netG_class=Generator,
#     pth_path=pth_path,
#     OUTPUT_DIR=OUTPUT_DIR,
#     folder_name="G_q17_list",
#     nz=100,
#     ngf=128,
#     device="cpu"
# )

# print("saved to:",save_dir)

int　→　Q1.7（8bit）   2進数表現

In [5]:
# def int8_to_bin8(v:int) -> str:
#     return format(v & 0xFF, "08b")

# def json_to_bin(save_dir: str, out_folder_name:str="bin_txt"):
#     meta_path = os.path.join(save_dir, "meta.json")
#     with open(meta_path, "r", encoding="utf-8") as f:
#         meta = json.load(f)

#     out_dir = os.path.join(save_dir, out_folder_name)
#     os.makedirs(out_dir, exist_ok=True)

#     for name, info in meta.items():
#         json_path = os.path.join(save_dir, info["json"])

#         with open(json_path, "r", encoding="utf-8") as f:
#             w_list = json.load(f)

#         txt_path = os.path.join(out_dir, f"{name}_weight_q17_bin.txt")
#         with open(txt_path, "w", encoding="utf-8") as ftxt:
#             ftxt.write(f"{name} weight (Q1.7) as 8-bit two's complement binary\n")
#             ftxt.write("shape = [out_ch][in_ch][4][4]\n")
#             ftxt.write("each value is 8 bit: b7..b0\n\n")

#             for out_ch_id,oc_block in enumerate(w_list):
#                 ftxt.write(f"=== out_ch {out_ch_id} === \n")
#                 for in_ch_id, kernel in enumerate(oc_block):
#                     ftxt.write(f"-- in_ch {in_ch_id} -- \n")
#                     for row in kernel:
#                         ftxt.write(" ".join(int8_to_bin8(v) for v in row) + "\n")
#                     ftxt.write("\n")
#     return out_dir

In [6]:
# save_dir = os.path.join(OUTPUT_DIR, "G_q17_list")
# bin_txt_dir = json_to_bin(save_dir=save_dir)
# print("save to:",bin_txt_dir)

### v1v2の読み込み

In [7]:
path = "output_train_3/v1v2.pth"

data = torch.load(path, map_location="cpu")
print(type(data))
print(data.keys())

v1 = data["v1"]
v2 = data["v2"]

print(v1)

<class 'dict'>
dict_keys(['v1', 'v2'])
tensor([ 1.5495e+00,  9.9641e-02,  5.3953e-01, -8.7803e-02, -1.5323e+00,
        -1.4779e+00, -1.5933e+00,  1.3963e+00,  2.0085e+00, -1.4041e-01,
         2.4191e+00, -6.1707e-01,  6.2796e-01, -9.7188e-03, -4.5521e-02,
        -2.3210e+00, -7.3280e-02, -4.7167e-01, -3.9119e-01, -4.3734e-01,
         1.6658e+00,  1.8472e+00,  7.2083e-02,  1.0563e+00,  2.4760e+00,
         8.5401e-01, -1.4381e+00,  3.0053e-01,  1.0244e+00,  1.0046e+00,
        -1.1581e+00,  8.8332e-01, -4.2478e-01,  1.0930e+00,  3.7062e-01,
        -3.8925e-02,  8.3142e-01,  2.9922e-01,  3.5718e-02,  7.3413e-01,
        -3.6172e-01, -1.1934e+00, -4.0869e-01, -1.0385e+00, -2.2052e+00,
        -1.5348e+00,  1.0818e+00,  9.9698e-01,  3.3059e-01,  1.2225e+00,
         5.9221e-02, -3.6542e-01, -8.7981e-01,  8.2682e-01,  1.6676e+00,
         4.8636e-01, -7.3226e-01,  2.5290e-01,  8.2823e-01, -2.4227e-01,
        -1.8179e-03, -3.2363e-03, -8.9691e-01,  1.4248e-01,  2.2267e-01,
         1.0

入力生成
-


In [37]:
#z = torch.randn(100).tanh()
# z = torch.randn(100)
# print(z)

z = [-0.0529,  1.3876, -0.1987, -0.6410, -0.4712, -1.2671,  1.5316, -0.3863,
        -1.3278, -0.3035, -1.4634,  0.3605,  1.0053,  1.2927, -0.5330, -0.8077,
         0.7029, -1.9641, -0.4360,  0.3952,  0.4549, -1.0385,  1.2419, -0.1570,
        -0.3820, -0.4848, -1.7011, -0.4536, -0.4430,  1.1325,  0.7088, -0.3032,
        -0.0947,  1.1591, -1.6729,  2.2497,  0.7753,  0.6680,  0.4857,  0.1887,
         1.6274,  0.8200, -2.4146, -0.4427, -0.9399, -1.0022,  0.5288,  0.4581,
         1.3886,  1.1309, -0.5669,  0.4439, -0.4753, -0.0873,  0.0265, -0.5976,
        -0.0388, -0.8068,  1.0560,  0.1182,  0.3832, -0.6784,  0.3612,  0.3288,
         0.3778,  0.8789, -0.4533, -1.0225, -0.2161, -0.0779, -1.4049, -0.6459,
         2.2251, -0.9339,  1.5322,  0.1074, -0.7073,  0.8982,  1.2360, -0.0968,
         0.7310, -0.3348,  0.0274, -0.5053,  1.1832, -2.0549, -0.7652, -0.9254,
         1.2167, -0.0393, -0.2366,  0.9378,  0.3727,  1.6377, -1.6947,  0.4398,
         0.3798, -0.6906, -0.5012, -0.4418]

##color
z = torch.tensor(z, dtype=torch.float32)
#z = z+v1
#z = z+v2

# z_q = float_to_int8(z)
# print(z_q)

逆畳み込み演算
-

1層目の演算 net0_weight_shape = (100,512,4,4)
-


z100次元[100,1,1] 1×1の画像が100枚　　 z_1,z_2, .. , z_100

karnelは[100,512,4,4] 4×4の画像が512×100枚　　k_1,k_2,...,k_512

z_1*k_1 + z_2*k_1 + ... + z_100*k_1 = output[0]
output[511]

--------------------------------------------

### float演算用

In [38]:
Q_FRAC_BITS = 7
Q_SCALE = 1 << Q_FRAC_BITS #128

### カーネルの準備　kernel[1][1]などの形式で使えるように

kernel[0][0]～kernel[99][511]まで

In [39]:
import numpy as np

path = os.path.join(OUTPUT_DIR, "G_q17_list", "net0_weight_q17_list.json")
with open(path, "r", encoding="utf-8") as f:
    w_list = json.load(f)

kernel_int8 = np.array(w_list, dtype=np.int8)
#add
kernel = kernel_int8.astype(np.float32) / Q_SCALE

print("karnelshape", kernel.shape)
print("kernel[0],[0]",kernel[99][511])

karnelshape (100, 512, 4, 4)
kernel[0],[0] [[-0.1171875  0.        -0.0234375 -0.015625 ]
 [ 0.1484375  0.        -0.015625   0.       ]
 [ 0.         0.0078125 -0.0625    -0.0390625]
 [ 0.03125   -0.0234375 -0.0234375 -0.0390625]]


### 1層目カーネルの計算　main

net0_calculateの計算　　z_1*k_[0][0] + z_2*k_[1][0] + ... + z_100*k_[100][0] = output[0]

100次元のzに対し、kernel[0][0]～kernel[100][0]を掛け合わせると、output0[1]になる。
これを512回行う。kernelは512×100枚ある。一列の計算で使用するのは100枚。

In [40]:
def net0_calculate_float(z_q,kernel,N):
    acc = np.zeros((4,4), dtype=np.float32)
    #kernel = kernel[::-1,::-1].astype(np.int64)

    for k in range(100):
        prod = np.float32(z_q[k])*kernel[k][N].astype(np.float32)
        acc += prod

    return acc

In [41]:
output0 = np.zeros((512, 4, 4), dtype=np.float32)

for i in range(512):
    output0[i] = net0_calculate_float(z,kernel,i)

# bit幅の検討
print("output0 min:", output0.min()) # -13.46
print("output0 max:", output0.max()) # 12.44

# ➡　候補１　Q6.9(16bit)  範囲±32  分解能1/512
# ➡　候補２　Q5.10(16bit) 範囲±16　分解能1/1024

# # nan/inf
# print("has NaN:", np.isnan(output0).any())
# print("has Inf:", np.isinf(output0).any())

output0_relu = np.maximum(output0, 0).astype(np.float32)

output0 = output0_relu

print("output0 min:", output0.min()) # 0
print("output0 max:", output0.max()) # 12.44

print("output0[0]",output0[0])
print("output0[1]",output0[1])
print("output0[1]",output0[511])

output0 min: -3.232227
output0 max: 3.2078953
output0 min: 0.0
output0 max: 3.2078953
output0[0] [[0.0000000e+00 1.4196014e-01 1.3126095e-01 4.0175554e-01]
 [0.0000000e+00 2.7191648e-01 0.0000000e+00 2.2010002e-01]
 [0.0000000e+00 7.5122118e-01 3.7656119e-04 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
output0[1] [[0.6690053  0.5256085  0.45054054 0.3464134 ]
 [0.         0.         0.2680641  0.2708039 ]
 [0.8233985  0.         0.         0.23135704]
 [0.         0.28888518 0.         0.        ]]
output0[1] [[1.1253048 0.        1.0822703 0.       ]
 [0.        0.        0.        0.       ]
 [0.        0.        1.3843467 0.1921203]
 [0.        0.        0.        0.       ]]


二層目　net2_weight_shape = (512,256,4,4)
-

ストライド処理（ 4×4 → 7×7 ）

In [42]:
def stride(kernel: np.ndarray, stride: int=2) -> np.ndarray:
    kH, kW = kernel.shape
    outH = (kH - 1) * stride + 1 # 7
    outW = (kW - 1) * stride + 1

    out = np.zeros((outH, outW), dtype=kernel.dtype)
    out[::stride, ::stride] = kernel
    return out

padding=1、kernel=4の分の0埋め。カーネル数-1分の０を追加し、padding分の0を削除。

今回は00で周囲を埋める。　7×7　→　11×11

In [44]:
def padding(kernel: np.ndarray, pad:int) -> np.ndarray:
    return np.pad(kernel,((pad,pad),(pad,pad)),mode="constant",constant_values=0)

###  入力の作成
　
１層目のoutput0[0]～output[511]が入力となる

input2[0]～input[511]にした

In [45]:
input2 = np.zeros((512, 11, 11), dtype=np.float32)

for i in range(512):
    kernel_up = stride(output0[i],stride=2)
    kernel_pad = padding(kernel_up,pad=2)
    input2[i] = kernel_pad

print("input2[1]",input2[0])
print("input2.shape",input2[1].shape)

input2[1] [[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.4196014e-01
  0.0000000e+00 1.3126095e-01 0.0000000e+00 4.0175554e-01 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 2.7191648e-01
  0.0000000e+00 0.0000000e+00 0.0000000e+00 2.2010002e-01 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [0.0000000e+00 0.000000

### 2層目のカーネルの取得

kernel2[0][0]～kernel2[511][255]

In [46]:
path = os.path.join(OUTPUT_DIR, "G_q17_list", "net1_weight_q17_list.json")
with open(path, "r", encoding="utf-8") as f:
    w_list = json.load(f)

kernel2_int8 = np.array(w_list, dtype=np.int8)
kernel2 = kernel2_int8.astype(np.float32) / Q_SCALE

print("karnelshape", kernel2.shape)
print("kernel[0][0]",kernel2[0][0])

karnelshape (512, 256, 4, 4)
kernel[0][0] [[-0.0390625  0.03125    0.0703125  0.0390625]
 [ 0.0078125 -0.0390625 -0.1015625  0.0390625]
 [-0.03125    0.0078125  0.0078125 -0.0078125]
 [-0.03125    0.0390625  0.046875  -0.015625 ]]


### 畳み込み演算の準備

input2.shape           (512,11,11)

input_split2.shape    (512,64,4,4)

input_split2[0][0]  ～　input_split2[511][63]

In [47]:
def split_11(img11):
    patches = np.zeros((64,4,4),dtype=img11.dtype)
    idx = 0
    for y in range(8):
        for x in range(8):
            patches[idx] = img11[y:y+4,x:x+4]
            idx += 1
    return patches

input_split2 = np.zeros((512,64,4,4),dtype=input2.dtype)

for N in range(0,512):
    input_split2[N] = split_11(input2[N])

# 確認
print(input2.shape)           # (512,11,11)
print(input_split2.shape)     # (512,64,4,4)

print("first patch (top-left):")
print(input_split2[0][0])

print("last patch (bottom-right):")
print(input_split2[511][63])

(512, 11, 11)
(512, 64, 4, 4)
first patch (top-left):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
last patch (bottom-right):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 畳み込み演算
input2[1]の分割input_split2[1][0]～input_split[1][63]に対して、kernel2[0][0]をかけていく。

input2[i]に対して、kernel2[i][0]をかけていく。



In [48]:
def conv4_float(split: np.ndarray, kernel:np.ndarray) -> np.float32:
    acc = np.float32(0)

    k = kernel[::-1,::-1].astype(np.float32)
    p = split.astype(np.float32)

    for y in range(4):
        for x in range(4):
            acc += p[y,x]*k[y,x]
    
    return np.float32(acc)

一列分の総和をとる。

In [49]:
def sum_out_float(out_q8_all):
    acc = np.sum(out_q8_all.astype(np.float32), axis=0)
    return acc.astype(np.float32)

def relu_float(x:np.ndarray) -> np.ndarray:
    return np.maximum(x,0).astype(np.float32)

今までの考え方を統合したコード

In [50]:
output2 = np.zeros((256,8,8),dtype=np.float32)
out_q8_all = np.zeros((512,8,8), dtype=np.float32)

for K in range(0,256):
    for N in range(0,512):
        out_q = np.zeros(64, dtype=np.float32)

        for i in range(64):
            out_q[i] = conv4_float(input_split2[N][i], kernel2[N][K])

        out_q8_all[N] = out_q.reshape(8,8)
    output2[K] = sum_out_float(out_q8_all)

print("output2 min:", output2.min()) # -47.34
print("output2 max:", output2.max()) # 20.94

# bit幅の計算
# 候補１　Q7.8(16bit) 範囲[-128,127.996] 分解能　1/256
# 候補２　Q6.9(16bit) 範囲[-64,63.998]   分解能　1/512


output2_relu = relu_float(output2)
output2 = output2_relu

print(output2[0])
print(output2[255])

output2 min: -16.071926
output2 max: 20.871885
[[ 1.7290925   0.          2.6437924   0.          0.6979478   0.
   2.2062516   0.        ]
 [ 0.          0.43303424  0.          2.1645494   0.          0.
   0.          1.207241  ]
 [ 0.67181164  0.          0.50492394  0.          2.206428    0.
   0.          0.        ]
 [ 0.          1.5852017   0.          1.6996046   0.          2.2885685
   0.          0.8907815 ]
 [ 3.7663758   0.          1.5796703   0.         10.093161    0.
   3.2630363   0.        ]
 [ 0.          0.8052603   0.          3.0350084   0.          0.
   0.          1.7885873 ]
 [ 0.48782787  0.          0.          0.          0.          1.2148963
   0.          0.        ]
 [ 0.          0.71830976  0.          1.2146802   0.59858114  0.21260326
   0.14549899  0.79429865]]
[[0.         0.         1.4817791  0.         0.         0.
  0.         0.        ]
 [1.5353988  0.         0.6749883  0.         0.         0.
  0.         0.        ]
 [0.         0. 

3層目　net3_weight_shape = (256,128,4,4)
-


### 入力の作成   

input3 (256, 19, 19)

In [51]:

input3 = np.zeros((256, 19, 19), dtype=np.float32)

for i in range(256):
    kernel_up = stride(output2[i],stride=2)
    kernel_pad = padding(kernel_up,pad=2)
    input3[i] = kernel_pad

# print("input3[0]",input3[0])
# print("input3[255]",input3[255])
# print("input3.shape",input3.shape)

### 3層目のカーネルの取得

kernel3[0][0]～kernel3[255][127]

In [52]:
path = os.path.join(OUTPUT_DIR, "G_q17_list", "net2_weight_q17_list.json")
with open(path, "r", encoding="utf-8") as f:
    w_list = json.load(f)

kernel3_int8 = np.array(w_list, dtype=np.int8)
kernel3 = kernel3_int8.astype(np.float32) / Q_SCALE

print("karnelshape", kernel3.shape)
print("kernel[0][0]",kernel3[0][127])

karnelshape (256, 128, 4, 4)
kernel[0][0] [[ 0.         0.        -0.015625  -0.0703125]
 [ 0.         0.0546875 -0.0234375  0.       ]
 [-0.0078125 -0.03125    0.03125   -0.0078125]
 [ 0.0703125 -0.0078125 -0.03125    0.0234375]]


### 畳み込み演算の準備

In [53]:
def split_19(img19):
    patches = np.zeros((256,4,4),dtype=img19.dtype)
    idx = 0
    for y in range(16):
        for x in range(16):
            patches[idx] = img19[y:y+4,x:x+4]
            idx += 1
    return patches

input_split3 = np.zeros((256,256,4,4),dtype=input3.dtype) # 256枚のカーネルがあり、それが256分割になる

for N in range(0,256):
    input_split3[N] = split_19(input3[N])

# 確認
print(input3.shape)           
print(input_split3.shape)     

print("first patch (top-left):")
print(input_split3[0][0])

print("last patch (bottom-right):")
print(input_split3[255][255])

(256, 19, 19)
(256, 256, 4, 4)
first patch (top-left):
[[0.        0.        0.        0.       ]
 [0.        0.        0.        0.       ]
 [0.        0.        1.7290925 0.       ]
 [0.        0.        0.        0.       ]]
last patch (bottom-right):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 畳み込み演算

In [54]:
output3 = np.zeros((128,16,16),dtype=np.float32)
out_q8_all = np.zeros((256,16,16), dtype=np.float32)

for K in range(0,128):
    for N in range(0,256):
        out_q = np.zeros(256, dtype=np.float32)

        for i in range(256):
            out_q[i] = conv4_float(input_split3[N][i], kernel3[N][K])

        out_q8_all[N] = out_q.reshape(16,16)
    output3[K] = sum_out_float(out_q8_all)

print("output3 min:", output3.min()) # -47.62
print("output3 max:", output3.max()) # 14.70

# bit幅の計算
# 候補１　Q7.8(16bit) 範囲[-128,127.996] 分解能　1/256
# 候補２　Q6.9(16bit) 範囲[-64,63.998]   分解能　1/512

output3_relu = relu_float(output3)
output3 = output3_relu

#print(output3[0])
print(output3[127])

output3 min: -21.604435
output3 max: 27.631655
[[2.1943521e+00 2.7315152e-01 5.1158541e-01 0.0000000e+00 1.8580415e+00
  0.0000000e+00 2.7573783e+00 1.8836260e-03 0.0000000e+00 9.4352371e-01
  3.7949946e+00 2.6200569e-01 2.7214067e+00 0.0000000e+00 7.6979041e-01
  0.0000000e+00]
 [6.1239028e+00 1.4473518e+00 2.2847779e+00 0.0000000e+00 3.3407608e-01
  2.0719826e+00 0.0000000e+00 0.0000000e+00 2.7435551e+00 0.0000000e+00
  1.1468625e+00 1.1048500e-01 5.6461854e+00 2.3464310e+00 1.1472915e+00
  4.0527418e-01]
 [2.8872159e+00 0.0000000e+00 2.5581992e+00 0.0000000e+00 0.0000000e+00
  1.5944618e-01 0.0000000e+00 0.0000000e+00 0.0000000e+00 8.6137247e-01
  0.0000000e+00 0.0000000e+00 0.0000000e+00 4.1490474e-01 2.5322003e+00
  6.5979731e-01]
 [3.1586370e+00 0.0000000e+00 9.7806716e-01 0.0000000e+00 0.0000000e+00
  0.0000000e+00 1.4949956e+00 0.0000000e+00 2.2482407e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 9.7533917e-01 2.9986579e+00
  1.7971959e+00]
 [1.1191497e+00 8.710

4層目　 net4_weight_shape = (128,1,4,4)
-

### 入力の作成
input4 (128, 35, 35)

In [25]:

input4 = np.zeros((128, 35, 35), dtype=np.float32)

for i in range(128):
    kernel_up = stride(output3[i],stride=2)
    kernel_pad = padding(kernel_up,pad=2)
    input4[i] = kernel_pad

print("input4[0]",input4[0])
print("input4[127]",input4[127])
print("input4.shape",input4.shape)

input4[0] [[0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.6910977 ... 0.        0.        0.       ]
 ...
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]]
input4[127] [[0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        1.4112993 ... 0.        0.        0.       ]
 ...
 [0.        0.        0.5196943 ... 0.767984  0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]
 [0.        0.        0.        ... 0.        0.        0.       ]]
input4.shape (128, 35, 35)


### 4層目のカーネルの取得

kerne4[0][0]～kernel4[127][0]

In [26]:
path = os.path.join(OUTPUT_DIR, "G_q17_list", "net3_weight_q17_list.json")
with open(path, "r", encoding="utf-8") as f:
    w_list = json.load(f)

kernel4_int8 = np.array(w_list, dtype=np.int8)
kernel4 = kernel4_int8.astype(np.float32) / Q_SCALE

print("karnelshape", kernel4.shape)
print("kernel[0][0]",kernel4[127][0])

karnelshape (128, 1, 4, 4)
kernel[0][0] [[-0.0078125  0.046875  -0.1171875 -0.1015625]
 [-0.0078125 -0.0234375  0.0234375 -0.1328125]
 [ 0.046875   0.015625   0.03125    0.0234375]
 [-0.0078125  0.03125    0.0546875  0.0078125]]


### 畳み込み演算の準備

In [27]:
def split_35(img35):
    patches = np.zeros((1024,4,4),dtype=img35.dtype)
    idx = 0
    for y in range(32):
        for x in range(32):
            patches[idx] = img35[y:y+4,x:x+4]
            idx += 1
    return patches

input_split4 = np.zeros((128,1024,4,4),dtype=input4.dtype) # 128枚のカーネルがあり、それが1024分割になる

for N in range(0,128):
    input_split4[N] = split_35(input4[N])

# 確認
print(input4.shape)           
print(input_split4.shape)     

print("first patch (top-left):")
print(input_split4[0][0])

print("last patch (bottom-right):")
print(input_split4[127][1023])

(128, 35, 35)
(128, 1024, 4, 4)
first patch (top-left):
[[0.        0.        0.        0.       ]
 [0.        0.        0.        0.       ]
 [0.        0.        0.6910977 0.       ]
 [0.        0.        0.        0.       ]]
last patch (bottom-right):
[[0.       0.       0.       0.      ]
 [0.       0.767984 0.       0.      ]
 [0.       0.       0.       0.      ]
 [0.       0.       0.       0.      ]]


### 畳み込み演算

In [28]:
output4 = np.zeros((1,32,32),dtype=np.float32)
out_q8_all = np.zeros((128,32,32), dtype=np.float32)

K=0
for N in range(0,128):
    out_q = np.zeros(1024, dtype=np.float32)
    for i in range(1024):
        out_q[i] = conv4_float(input_split4[N][i], kernel4[N][K])
    out_q8_all[N] = out_q.reshape(32,32)
output4[K] = sum_out_float(out_q8_all)


print(output4.shape)
print(output4)


(1, 32, 32)
[[[-2.596958  -3.3562346 -5.000489  ... -0.7988238 -2.5049083 -4.0401435]
  [-2.0855713 -1.6494095 -1.528937  ... -1.9437722 -3.7178278 -5.693359 ]
  [-3.0051188 -2.693488  -2.409134  ... -2.7201548 -3.9621549 -6.298702 ]
  ...
  [-1.8730594 -2.1641078 -2.76598   ... -3.6948276 -3.1563585 -2.5552197]
  [-2.0721393 -2.6001241 -2.2707198 ... -2.6162825 -3.661386  -2.26535  ]
  [-3.1906798 -4.3863516 -3.3164992 ... -2.4419303 -4.0042653 -3.3044388]]]


### tanh

In [29]:
output4 = np.tanh(output4)
print(output4.shape)
print(output4)

(1, 32, 32)
[[[-0.9889608  -0.99757165 -0.99990934 ... -0.6633787  -0.9867442
   -0.99938107]
  [-0.96959996 -0.9287765  -0.9102425  ... -0.959832   -0.998821
   -0.99997735]
  [-0.995105   -0.9908901  -0.98396796 ... -0.9913612  -0.9992766
   -0.9999932 ]
  ...
  [-0.95387065 -0.97396135 -0.9921148  ... -0.9987655  -0.9963804
   -0.9880055 ]
  [-0.96878517 -0.9890301  -0.97890866 ... -0.9893771  -0.99868023
   -0.97868335]
  [-0.9966201  -0.9996903  -0.9973711  ... -0.9849782  -0.99933505
   -0.99730694]]]


画像出力
-


float

In [30]:
from PIL import Image
import numpy as np


img = output4[0]
img = (img+1.0)*0.5
img = np.clip(img, 0.0, 1.0)
img_u8 = (img * 255).astype(np.uint8)

Image.fromarray(img_u8,mode="L").save("output_float_B.png")


カラー化（RGBそれぞれを保存済み想定）

In [31]:
img_R = Image.open("output_float.png").convert("L")
img_G = Image.open("output_float_G.png").convert("L")
img_B = Image.open("output_float_B.png").convert("L")

# Numpy
R = np.array(img_R, dtype=np.uint8)
G = np.array(img_G, dtype=np.uint8)
B = np.array(img_B, dtype=np.uint8)

# RGB合成
rgb = np.stack([R,G,B], axis=2)
img_RGB = Image.fromarray(rgb, mode="RGB")

H,W = R.shape
canvas = Image.new("RGB",(W*4,H))

canvas.paste(img_R.convert("RGB"),(0*W,0))
canvas.paste(img_G.convert("RGB"),(1*W,0))
canvas.paste(img_B.convert("RGB"),(2*W,0))
canvas.paste(img_RGB,             (3*W,0))

canvas.save("output_color.png")